---
# https://certbot.eff.org/#ubuntuxenial-nginx
- name: Add PPA for Certbot.
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
    update_cache: yes
  register: certbot_ppa_added

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false

- name: Ensure Certbot is installed.
  apt:
    name: certbot
    state: installed

- name: Install nginx site for letsencrypt requests
  template:
    src: templates/nginx-http.j2
    dest: /etc/nginx/sites-enabled/http

- name: Create letsencrypt certificate
  #shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt/ -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  shell: certbot certonly --webroot -w /var/www/letsencrypt/ -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} --non-interactive
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
