---
- include_vars: "vars/default.yml"

- name: apt-get update
  apt:
    update_cache=yes
  become: True

- name: install required packages for Docker
  apt:
    name="{{ item }}"
    state=latest
    force=yes
  become: True
  with_items:
    - ntp
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python-pip
    - openssl
  tags:
    - packages
    - docker

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: True

- name: Add PPA for Docker.
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
    state: present
    update_cache: yes
  register: docker_ppa_added

- name: apt-get update
  apt:
    update_cache=yes
  become: true

- name: Install Docker CE.
  apt: pkg=docker-ce=17.06.0~ce-0~ubuntu state=present

- name: Run test docker image
  shell: docker run hello-world
  register: docker_test_run
  failed_when: "docker_test_run.rc != 0"

- name: install docker-py
  pip: 
    name: docker-py
    version: 1.10.6

- name: Restart a container
  docker_container:
    name: HTTPServer
    image: infynyxx/infynyxxcom_http_server:latest
    state: started
    restart_policy: unless-stopped
    #restart: yes
    pull: true
    ports:
     - "127.0.0.1:8080:8080" # if host is not provided it will bind to 0.0.0.0 and will be exposed to internet
  register: docker_container

- name: Show docker_container
  debug: var=docker_container
